import time
import itertools

start = time.time()
#  Q.44
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
# Sol.44
def penta(n):
    return n*(3*n-1)/2

a=[]
for i in range(1,3000):
    a.append(int(penta(i)))


for j in a:
    for k in a:
        if j>k:
            if j+k in a:
                result = j-k
                if result in a:
                    print(result)
                    break
# def problem044():
# 	formula = lambda x : x*(3*x-1)/2
# 	penta = {int(formula(i)) for i in range(1,3000)}
#
# 	for i in penta:
# 		for j in penta:
# 			if i > j:
# 				if i+j in penta:
# 					result = i-j
# 					if result in penta:
# 						print(result)
# 						break
problem044()
# A.44
end = time.time() - start
print(end)
