import time


start = time.time()
#  Q.45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
# Sol.45
def tri(n):
    return int(n*(n+1)/2)
def penta(n):
    return (n*(3*n-1)/2)
def hexa(n):
    return n*(2*n-1)
# #삼각수와 육각수의 관계는 (삼각수계수) = (육각수계수)*2 - 1

 
A=[]
B=[]
n=1
while n<=100000:
    A.append(penta(n))
    B.append(hexa(n))
    n=n+1
X=set(A)
Y=set(B)

print(X & Y)
# A.45
# 1533776805
# j=27693
# 삼각수 계수 = 55385
# print(tri(55835))art
end = time.time() - start
print(end)

